language: php

php:
    - 5.6

before_install:
    - sudo add-apt-repository -y ppa:ondrej/php5-5.6
    - sudo apt-get update -qq
    - sudo apt-get install -qq libssl-dev php5-dev
    
install:
    - |
        git clone git://github.com/bitcoin/secp256k1.git libsecp256k1 \
        && cd libsecp256k1 \
        && ./autogen.sh && ./configure && make && sudo make install \
        && cd ..
    - |
        cd secp256k1 \
        && phpize && ./configure --with-secp256k1 && make && sudo make install \
        && cd ..
    - composer update

script:
    - php -dextension=secp256k1.so vendor/phpunit/phpunit/phpunit --debug tests/
